### ISSUE TITLE
Wrong field name for primitive topology when exporting

### ISSUE THREAD

**Issue by Cyphall** [spnda/fastgltf#54]
When exporting a glTF file, the topology of primitives is exported in a field called "type":
https://github.com/spnda/fastgltf/blob/753b1610fe161963ba7242b65b744d7927b11303/src/fastgltf.cpp#L4939-L4941

But the specs say that [this field should be called "mode"](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_mesh_primitive_mode).

**Comment by spnda** [comment]
First of all, thank you for all of the issues you've found over the past few days and sorry that you had to face them.

For the future, in these cases where the fix is obvious and/or trivial perhaps you could open a pull request directly? I am often at school where I have no way of committing and/or testing changes, and you've always found a correct solution for the issue which you mentioned in the issue. I'd be happy to review and merge those.

**Comment by Cyphall** [comment]
> First of all, thank you for all of the issues you've found over the past few days and sorry that you had to face them.

It's normal, export is a fairly new feature and you don't have the resources a company would have to fully test it before release :smiley:

> For the future, in these cases where the fix is obvious and/or trivial perhaps you could open a pull request directly?

Sure!
